tasks:
  - init: |
      # Build module
      yarn && yarn build

      # Install Nuxt example
      .gitpod/scripts/nuxt-setup.sh

# VScode xdebug extension
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - felixfbecker.php-debug
    - octref.vetur

ports:
  # Nuxt
  - port: 3000
    onOpen: ignore
    visibility: public

  # Nuxt Storybook
  - port: 3003
    onOpen: ignore
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: true
